### ISSUE TITLE
Where to find anova_ble library?

### ISSUE THREAD

**Issue by filmkorn** [ninjawarrior1337/hass_anova_ble#16]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The code imports from `anova_ble` but I can only find the library on pypi.
Any chance you could make the source project public? I'm wondering if I could integrate the Nano into it.

### Describe the solution you'd like

anova_ble on github.

### Describe alternatives you've considered

Downloading the tar.gz source bundle from pypi.

### Additional context

Cannot contribute to the source on pypi.

**Comment by ninjawarrior1337** [comment]
Here is the link to the repo, 
https://github.com/ninjawarrior1337/anova_ble

I'll be honest though, the library in its current state is not structured for more devices other than the original precision cooker. You are more than welcome to adapt it to support more than just that sous vide machine.
